require "travis/notifications/notifiers/campfire"
require "travis/notifications/notifiers/email"
require "travis/notifications/notifiers/flowdock"
require "travis/notifications/notifiers/github_status"
require "travis/notifications/notifiers/hipchat"
require "travis/notifications/notifiers/irc"
require "travis/notifications/notifiers/pusher"
require "travis/notifications/notifiers/webhook"
