require "travis/tasks/notifiers/campfire"
require "travis/tasks/notifiers/email"
require "travis/tasks/notifiers/flowdock"
require "travis/tasks/notifiers/github_status"
require "travis/tasks/notifiers/hipchat"
require "travis/tasks/notifiers/irc"
require "travis/tasks/notifiers/pusher"
require "travis/tasks/notifiers/webhook"
